<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE scheme>
<body>
 <scheme_header>
  <version>1.0</version>
 </scheme_header>
 <elements>
  <element id="CLink:5" typeID="CLink" nodeType="rootNode">
   <properties>
    <objectName>CLink</objectName>
    <opacity>1</opacity>
    <enabled>true</enabled>
    <visible>true</visible>
    <x>0</x>
    <y>0</y>
    <z>0</z>
    <rotation>0</rotation>
    <scale>1</scale>
    <width>0</width>
    <height>0</height>
    <nomber>5</nomber>
    <name></name>
    <resultID>CAmp:0:CResult:0</resultID>
    <argumentID>CAmp:2:CArgument:0</argumentID>
   </properties>
   <children/>
  </element>
  <element id="CAmp:2" typeID="CAmp" nodeType="rootNode">
   <properties>
    <objectName>CAmp</objectName>
    <opacity>1</opacity>
    <enabled>true</enabled>
    <visible>true</visible>
    <x>280</x>
    <y>16</y>
    <z>0</z>
    <rotation>0</rotation>
    <scale>1</scale>
    <width>0</width>
    <height>0</height>
    <nomber>2</nomber>
    <name></name>
    <gain>1</gain>
   </properties>
   <children>
    <element id="CAmp:2:CArgument:0" typeID="CArgument" nodeType="subNode">
     <properties>
      <objectName>CArgument</objectName>
      <opacity>1</opacity>
      <enabled>true</enabled>
      <visible>true</visible>
      <x>38</x>
      <y>2.5</y>
      <z>0</z>
      <rotation>0</rotation>
      <scale>1</scale>
      <width>0</width>
      <height>0</height>
      <nomber>0</nomber>
      <name>X</name>
      <portalOrientation>2</portalOrientation>
      <dataColor>@Color(210 228 89 180)</dataColor>
     </properties>
     <children/>
    </element>
    <element id="CAmp:2:CResult:0" typeID="CResult" nodeType="subNode">
     <properties>
      <objectName>CResult</objectName>
      <opacity>1</opacity>
      <enabled>true</enabled>
      <visible>true</visible>
      <x>-19.72360679775</x>
      <y>2.5</y>
      <z>0</z>
      <rotation>0</rotation>
      <scale>1</scale>
      <width>0</width>
      <height>0</height>
      <nomber>0</nomber>
      <name>Y</name>
      <portalOrientation>0</portalOrientation>
      <dataColor>@Color(78 131 181 180)</dataColor>
     </properties>
     <children/>
    </element>
   </children>
  </element>
  <element id="CLink:4" typeID="CLink" nodeType="rootNode">
   <properties>
    <objectName>CLink</objectName>
    <opacity>1</opacity>
    <enabled>true</enabled>
    <visible>true</visible>
    <x>0</x>
    <y>0</y>
    <z>0</z>
    <rotation>0</rotation>
    <scale>1</scale>
    <width>0</width>
    <height>0</height>
    <nomber>4</nomber>
    <name></name>
    <resultID>CAmp:1:CResult:0</resultID>
    <argumentID>CSum:0:CArgument:2</argumentID>
   </properties>
   <children/>
  </element>
  <element id="CLink:3" typeID="CLink" nodeType="rootNode">
   <properties>
    <objectName>CLink</objectName>
    <opacity>1</opacity>
    <enabled>true</enabled>
    <visible>true</visible>
    <x>0</x>
    <y>0</y>
    <z>0</z>
    <rotation>0</rotation>
    <scale>1</scale>
    <width>0</width>
    <height>0</height>
    <nomber>3</nomber>
    <name></name>
    <resultID>CAmp:0:CResult:0</resultID>
    <argumentID>CAmp:1:CArgument:0</argumentID>
   </properties>
   <children/>
  </element>
  <element id="CLink:2" typeID="CLink" nodeType="rootNode">
   <properties>
    <objectName>CLink</objectName>
    <opacity>1</opacity>
    <enabled>true</enabled>
    <visible>true</visible>
    <x>0</x>
    <y>0</y>
    <z>0</z>
    <rotation>0</rotation>
    <scale>1</scale>
    <width>0</width>
    <height>0</height>
    <nomber>2</nomber>
    <name></name>
    <resultID>CAmp:0:CResult:0</resultID>
    <argumentID>CCSVOut:0:CArgument:0</argumentID>
   </properties>
   <children/>
  </element>
  <element id="CLink:1" typeID="CLink" nodeType="rootNode">
   <properties>
    <objectName>CLink</objectName>
    <opacity>1</opacity>
    <enabled>true</enabled>
    <visible>true</visible>
    <x>0</x>
    <y>0</y>
    <z>0</z>
    <rotation>0</rotation>
    <scale>1</scale>
    <width>0</width>
    <height>0</height>
    <nomber>1</nomber>
    <name></name>
    <resultID>CSum:0:CResult:0</resultID>
    <argumentID>CAmp:0:CArgument:0</argumentID>
   </properties>
   <children/>
  </element>
  <element id="CLink:0" typeID="CLink" nodeType="rootNode">
   <properties>
    <objectName>CLink</objectName>
    <opacity>1</opacity>
    <enabled>true</enabled>
    <visible>true</visible>
    <x>0</x>
    <y>0</y>
    <z>0</z>
    <rotation>0</rotation>
    <scale>1</scale>
    <width>0</width>
    <height>0</height>
    <nomber>0</nomber>
    <name></name>
    <resultID>CStepExcitation:0:CResult:0</resultID>
    <argumentID>CSum:0:CArgument:0</argumentID>
   </properties>
   <children/>
  </element>
  <element id="CAmp:1" typeID="CAmp" nodeType="rootNode">
   <properties>
    <objectName>CAmp</objectName>
    <opacity>1</opacity>
    <enabled>true</enabled>
    <visible>true</visible>
    <x>280</x>
    <y>136</y>
    <z>0</z>
    <rotation>0</rotation>
    <scale>1</scale>
    <width>0</width>
    <height>0</height>
    <nomber>1</nomber>
    <name></name>
    <gain>1</gain>
   </properties>
   <children>
    <element id="CAmp:1:CArgument:0" typeID="CArgument" nodeType="subNode">
     <properties>
      <objectName>CArgument</objectName>
      <opacity>1</opacity>
      <enabled>true</enabled>
      <visible>true</visible>
      <x>37</x>
      <y>2.5</y>
      <z>0</z>
      <rotation>0</rotation>
      <scale>1</scale>
      <width>0</width>
      <height>0</height>
      <nomber>0</nomber>
      <name>X</name>
      <portalOrientation>2</portalOrientation>
      <dataColor>@Color(210 228 89 180)</dataColor>
     </properties>
     <children/>
    </element>
    <element id="CAmp:1:CResult:0" typeID="CResult" nodeType="subNode">
     <properties>
      <objectName>CResult</objectName>
      <opacity>1</opacity>
      <enabled>true</enabled>
      <visible>true</visible>
      <x>-19.72360679775</x>
      <y>2.5</y>
      <z>0</z>
      <rotation>0</rotation>
      <scale>1</scale>
      <width>0</width>
      <height>0</height>
      <nomber>0</nomber>
      <name>Y</name>
      <portalOrientation>0</portalOrientation>
      <dataColor>@Color(219 44 190 180)</dataColor>
     </properties>
     <children/>
    </element>
   </children>
  </element>
  <element id="CCSVOut:0" typeID="CCSVOut" nodeType="rootNode">
   <properties>
    <objectName>CCSVOut</objectName>
    <opacity>1</opacity>
    <enabled>true</enabled>
    <visible>true</visible>
    <x>432</x>
    <y>72</y>
    <z>0</z>
    <rotation>0</rotation>
    <scale>1</scale>
    <width>0</width>
    <height>0</height>
    <nomber>0</nomber>
    <name></name>
   </properties>
   <children>
    <element id="CCSVOut:0:CArgument:0" typeID="CArgument" nodeType="subNode">
     <properties>
      <objectName>CArgument</objectName>
      <opacity>1</opacity>
      <enabled>true</enabled>
      <visible>true</visible>
      <x>-19.72360679775</x>
      <y>2.5</y>
      <z>0</z>
      <rotation>0</rotation>
      <scale>1</scale>
      <width>0</width>
      <height>0</height>
      <nomber>0</nomber>
      <name>X</name>
      <portalOrientation>0</portalOrientation>
      <dataColor>@Color(210 228 89 180)</dataColor>
     </properties>
     <children/>
    </element>
   </children>
  </element>
  <element id="CAmp:0" typeID="CAmp" nodeType="rootNode">
   <properties>
    <objectName>CAmp</objectName>
    <opacity>1</opacity>
    <enabled>true</enabled>
    <visible>true</visible>
    <x>280</x>
    <y>72</y>
    <z>0</z>
    <rotation>0</rotation>
    <scale>1</scale>
    <width>0</width>
    <height>0</height>
    <nomber>0</nomber>
    <name></name>
    <gain>1</gain>
   </properties>
   <children>
    <element id="CAmp:0:CArgument:0" typeID="CArgument" nodeType="subNode">
     <properties>
      <objectName>CArgument</objectName>
      <opacity>1</opacity>
      <enabled>true</enabled>
      <visible>true</visible>
      <x>-19.72360679775</x>
      <y>2.5</y>
      <z>0</z>
      <rotation>0</rotation>
      <scale>1</scale>
      <width>0</width>
      <height>0</height>
      <nomber>0</nomber>
      <name>X</name>
      <portalOrientation>0</portalOrientation>
      <dataColor>@Color(122 149 206 180)</dataColor>
     </properties>
     <children/>
    </element>
    <element id="CAmp:0:CResult:0" typeID="CResult" nodeType="subNode">
     <properties>
      <objectName>CResult</objectName>
      <opacity>1</opacity>
      <enabled>true</enabled>
      <visible>true</visible>
      <x>38</x>
      <y>2.5</y>
      <z>0</z>
      <rotation>0</rotation>
      <scale>1</scale>
      <width>0</width>
      <height>0</height>
      <nomber>0</nomber>
      <name>Y</name>
      <portalOrientation>2</portalOrientation>
      <dataColor>@Color(210 228 89 180)</dataColor>
     </properties>
     <children/>
    </element>
   </children>
  </element>
  <element id="CSum:0" typeID="CSum" nodeType="rootNode">
   <properties>
    <objectName>CSum</objectName>
    <opacity>1</opacity>
    <enabled>true</enabled>
    <visible>true</visible>
    <x>144</x>
    <y>72</y>
    <z>0</z>
    <rotation>0</rotation>
    <scale>1</scale>
    <width>0</width>
    <height>0</height>
    <nomber>0</nomber>
    <name></name>
   </properties>
   <children>
    <element id="CSum:0:CArgument:0" typeID="CArgument" nodeType="subNode">
     <properties>
      <objectName>CArgument</objectName>
      <opacity>1</opacity>
      <enabled>true</enabled>
      <visible>true</visible>
      <x>-21.72360679775</x>
      <y>2.5</y>
      <z>0</z>
      <rotation>0</rotation>
      <scale>1</scale>
      <width>0</width>
      <height>0</height>
      <nomber>0</nomber>
      <name>In</name>
      <portalOrientation>0</portalOrientation>
      <dataColor>@Color(49 144 0 180)</dataColor>
     </properties>
     <children/>
    </element>
    <element id="CSum:0:CArgument:1" typeID="CArgument" nodeType="subNode">
     <properties>
      <objectName>CArgument</objectName>
      <opacity>1</opacity>
      <enabled>true</enabled>
      <visible>true</visible>
      <x>12</x>
      <y>-24.72360679775</y>
      <z>0</z>
      <rotation>0</rotation>
      <scale>1</scale>
      <width>0</width>
      <height>0</height>
      <nomber>1</nomber>
      <name>X1</name>
      <portalOrientation>1</portalOrientation>
      <dataColor>@Color(255 255 255 0)</dataColor>
     </properties>
     <children/>
    </element>
    <element id="CSum:0:CArgument:2" typeID="CArgument" nodeType="subNode">
     <properties>
      <objectName>CArgument</objectName>
      <opacity>1</opacity>
      <enabled>true</enabled>
      <visible>true</visible>
      <x>11.5</x>
      <y>20</y>
      <z>0</z>
      <rotation>0</rotation>
      <scale>1</scale>
      <width>0</width>
      <height>0</height>
      <nomber>2</nomber>
      <name>X2</name>
      <portalOrientation>3</portalOrientation>
      <dataColor>@Color(219 44 190 180)</dataColor>
     </properties>
     <children/>
    </element>
    <element id="CSum:0:CResult:0" typeID="CResult" nodeType="subNode">
     <properties>
      <objectName>CResult</objectName>
      <opacity>1</opacity>
      <enabled>true</enabled>
      <visible>true</visible>
      <x>37</x>
      <y>2.5</y>
      <z>0</z>
      <rotation>0</rotation>
      <scale>1</scale>
      <width>0</width>
      <height>0</height>
      <nomber>0</nomber>
      <name>Sum</name>
      <portalOrientation>2</portalOrientation>
      <dataColor>@Color(122 149 206 180)</dataColor>
     </properties>
     <children/>
    </element>
   </children>
  </element>
  <element id="CStepExcitation:0" typeID="CStepExcitation" nodeType="rootNode">
   <properties>
    <objectName>CStepExcitation</objectName>
    <opacity>1</opacity>
    <enabled>true</enabled>
    <visible>true</visible>
    <x>24</x>
    <y>72</y>
    <z>0</z>
    <rotation>0</rotation>
    <scale>1</scale>
    <width>0</width>
    <height>0</height>
    <nomber>0</nomber>
    <name></name>
   </properties>
   <children>
    <element id="CStepExcitation:0:CResult:0" typeID="CResult" nodeType="subNode">
     <properties>
      <objectName>CResult</objectName>
      <opacity>1</opacity>
      <enabled>true</enabled>
      <visible>true</visible>
      <x>36</x>
      <y>2.5</y>
      <z>0</z>
      <rotation>0</rotation>
      <scale>1</scale>
      <width>0</width>
      <height>0</height>
      <nomber>0</nomber>
      <name>Out</name>
      <portalOrientation>2</portalOrientation>
      <dataColor>@Color(49 144 0 180)</dataColor>
     </properties>
     <children/>
    </element>
   </children>
  </element>
 </elements>
</body>
