<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE scheme>
<body>
 <scheme_header>
  <version>1.0</version>
 </scheme_header>
 <elements>
  <element nodeType="rootNode" id="CStepExcitation:0" typeID="CStepExcitation">
   <properties>
    <objectName>CStepExcitation</objectName>
    <opacity>1</opacity>
    <enabled>true</enabled>
    <visible>true</visible>
    <x>152</x>
    <y>112</y>
    <z>0</z>
    <rotation>0</rotation>
    <scale>1</scale>
    <width>0</width>
    <height>0</height>
    <nomber>0</nomber>
    <name></name>
   </properties>
   <children>
    <element nodeType="subNode" id="CStepExcitation:0:CResult:0" typeID="CResult">
     <properties>
      <objectName>CResult</objectName>
      <opacity>1</opacity>
      <enabled>true</enabled>
      <visible>true</visible>
      <x>36</x>
      <y>2.5</y>
      <z>0</z>
      <rotation>0</rotation>
      <scale>1</scale>
      <width>0</width>
      <height>0</height>
      <nomber>0</nomber>
      <name>Out</name>
      <portalOrientation>2</portalOrientation>
      <dataColor>@Color(78 131 181 180)</dataColor>
     </properties>
     <children/>
    </element>
   </children>
  </element>
  <element nodeType="rootNode" id="CSum:0" typeID="CSum">
   <properties>
    <objectName>CSum</objectName>
    <opacity>1</opacity>
    <enabled>true</enabled>
    <visible>true</visible>
    <x>296</x>
    <y>112</y>
    <z>0</z>
    <rotation>0</rotation>
    <scale>1</scale>
    <width>0</width>
    <height>0</height>
    <nomber>0</nomber>
    <name></name>
   </properties>
   <children>
    <element nodeType="subNode" id="CSum:0:CArgument:0" typeID="CArgument">
     <properties>
      <objectName>CArgument</objectName>
      <opacity>1</opacity>
      <enabled>true</enabled>
      <visible>true</visible>
      <x>-21.72360679775</x>
      <y>2.5</y>
      <z>0</z>
      <rotation>0</rotation>
      <scale>1</scale>
      <width>0</width>
      <height>0</height>
      <nomber>0</nomber>
      <name>In</name>
      <portalOrientation>0</portalOrientation>
      <dataColor>@Color(78 131 181 180)</dataColor>
     </properties>
     <children/>
    </element>
    <element nodeType="subNode" id="CSum:0:CArgument:1" typeID="CArgument">
     <properties>
      <objectName>CArgument</objectName>
      <opacity>1</opacity>
      <enabled>true</enabled>
      <visible>true</visible>
      <x>12</x>
      <y>-24.72360679775</y>
      <z>0</z>
      <rotation>0</rotation>
      <scale>1</scale>
      <width>0</width>
      <height>0</height>
      <nomber>1</nomber>
      <name>X1</name>
      <portalOrientation>1</portalOrientation>
      <dataColor>@Color(255 255 255 255)</dataColor>
     </properties>
     <children/>
    </element>
    <element nodeType="subNode" id="CSum:0:CArgument:2" typeID="CArgument">
     <properties>
      <objectName>CArgument</objectName>
      <opacity>1</opacity>
      <enabled>true</enabled>
      <visible>true</visible>
      <x>11.5</x>
      <y>20</y>
      <z>0</z>
      <rotation>0</rotation>
      <scale>1</scale>
      <width>0</width>
      <height>0</height>
      <nomber>2</nomber>
      <name>X2</name>
      <portalOrientation>3</portalOrientation>
      <dataColor>@Color(1 30 114 180)</dataColor>
     </properties>
     <children/>
    </element>
    <element nodeType="subNode" id="CSum:0:CResult:0" typeID="CResult">
     <properties>
      <objectName>CResult</objectName>
      <opacity>1</opacity>
      <enabled>true</enabled>
      <visible>true</visible>
      <x>37</x>
      <y>2.5</y>
      <z>0</z>
      <rotation>0</rotation>
      <scale>1</scale>
      <width>0</width>
      <height>0</height>
      <nomber>0</nomber>
      <name>Sum</name>
      <portalOrientation>2</portalOrientation>
      <dataColor>@Color(93 23 4 180)</dataColor>
     </properties>
     <children/>
    </element>
   </children>
  </element>
  <element nodeType="rootNode" id="CTransLink:0" typeID="CTransLink">
   <properties>
    <objectName>CTransLink</objectName>
    <opacity>1</opacity>
    <enabled>true</enabled>
    <visible>true</visible>
    <x>464</x>
    <y>112</y>
    <z>0</z>
    <rotation>0</rotation>
    <scale>1</scale>
    <width>0</width>
    <height>0</height>
    <nomber>0</nomber>
    <name></name>
    <selectedTLAlg>0</selectedTLAlg>
    <factorSeparator>;</factorSeparator>
    <nomFactors>0.8</nomFactors>
    <denomFactors>1;0.7;0.08</denomFactors>
   </properties>
   <children>
    <element nodeType="subNode" id="CTransLink:0:CArgument:0" typeID="CArgument">
     <properties>
      <objectName>CArgument</objectName>
      <opacity>1</opacity>
      <enabled>true</enabled>
      <visible>true</visible>
      <x>-21.72360679775</x>
      <y>2.5</y>
      <z>0</z>
      <rotation>0</rotation>
      <scale>1</scale>
      <width>0</width>
      <height>0</height>
      <nomber>0</nomber>
      <name>In</name>
      <portalOrientation>0</portalOrientation>
      <dataColor>@Color(93 23 4 180)</dataColor>
     </properties>
     <children/>
    </element>
    <element nodeType="subNode" id="CTransLink:0:CResult:0" typeID="CResult">
     <properties>
      <objectName>CResult</objectName>
      <opacity>1</opacity>
      <enabled>true</enabled>
      <visible>true</visible>
      <x>28</x>
      <y>2.5</y>
      <z>0</z>
      <rotation>0</rotation>
      <scale>1</scale>
      <width>0</width>
      <height>0</height>
      <nomber>0</nomber>
      <name>Out</name>
      <portalOrientation>2</portalOrientation>
      <dataColor>@Color(252 42 38 180)</dataColor>
     </properties>
     <children/>
    </element>
   </children>
  </element>
  <element nodeType="rootNode" id="CCSVOut:0" typeID="CCSVOut">
   <properties>
    <objectName>CCSVOut</objectName>
    <opacity>1</opacity>
    <enabled>true</enabled>
    <visible>true</visible>
    <x>672</x>
    <y>112</y>
    <z>0</z>
    <rotation>0</rotation>
    <scale>1</scale>
    <width>0</width>
    <height>0</height>
    <nomber>0</nomber>
    <name></name>
   </properties>
   <children>
    <element nodeType="subNode" id="CCSVOut:0:CArgument:0" typeID="CArgument">
     <properties>
      <objectName>CArgument</objectName>
      <opacity>1</opacity>
      <enabled>true</enabled>
      <visible>true</visible>
      <x>-19.72360679775</x>
      <y>2.5</y>
      <z>0</z>
      <rotation>0</rotation>
      <scale>1</scale>
      <width>0</width>
      <height>0</height>
      <nomber>0</nomber>
      <name>X</name>
      <portalOrientation>0</portalOrientation>
      <dataColor>@Color(252 42 38 180)</dataColor>
     </properties>
     <children/>
    </element>
   </children>
  </element>
  <element nodeType="rootNode" id="CTransLink:1" typeID="CTransLink">
   <properties>
    <objectName>CTransLink</objectName>
    <opacity>1</opacity>
    <enabled>true</enabled>
    <visible>true</visible>
    <x>464</x>
    <y>216</y>
    <z>0</z>
    <rotation>0</rotation>
    <scale>1</scale>
    <width>0</width>
    <height>0</height>
    <nomber>1</nomber>
    <name></name>
    <selectedTLAlg>0</selectedTLAlg>
    <factorSeparator>;</factorSeparator>
    <nomFactors>0.8</nomFactors>
    <denomFactors>1;0.7;0.08</denomFactors>
   </properties>
   <children>
    <element nodeType="subNode" id="CTransLink:1:CArgument:0" typeID="CArgument">
     <properties>
      <objectName>CArgument</objectName>
      <opacity>1</opacity>
      <enabled>true</enabled>
      <visible>true</visible>
      <x>27</x>
      <y>2.5</y>
      <z>0</z>
      <rotation>0</rotation>
      <scale>1</scale>
      <width>0</width>
      <height>0</height>
      <nomber>0</nomber>
      <name>In</name>
      <portalOrientation>2</portalOrientation>
      <dataColor>@Color(252 42 38 180)</dataColor>
     </properties>
     <children/>
    </element>
    <element nodeType="subNode" id="CTransLink:1:CResult:0" typeID="CResult">
     <properties>
      <objectName>CResult</objectName>
      <opacity>1</opacity>
      <enabled>true</enabled>
      <visible>true</visible>
      <x>-28.72360679775</x>
      <y>2.5</y>
      <z>0</z>
      <rotation>0</rotation>
      <scale>1</scale>
      <width>0</width>
      <height>0</height>
      <nomber>0</nomber>
      <name>Out</name>
      <portalOrientation>0</portalOrientation>
      <dataColor>@Color(1 30 114 180)</dataColor>
     </properties>
     <children/>
    </element>
   </children>
  </element>
  <element nodeType="rootNode" id="CLink:0" typeID="CLink">
   <properties>
    <objectName>CLink</objectName>
    <opacity>1</opacity>
    <enabled>true</enabled>
    <visible>true</visible>
    <x>0</x>
    <y>0</y>
    <z>0</z>
    <rotation>0</rotation>
    <scale>1</scale>
    <width>0</width>
    <height>0</height>
    <nomber>0</nomber>
    <name></name>
    <resultID>CStepExcitation:0:CResult:0</resultID>
    <argumentID>CSum:0:CArgument:0</argumentID>
   </properties>
   <children/>
  </element>
  <element nodeType="rootNode" id="CLink:1" typeID="CLink">
   <properties>
    <objectName>CLink</objectName>
    <opacity>1</opacity>
    <enabled>true</enabled>
    <visible>true</visible>
    <x>0</x>
    <y>0</y>
    <z>0</z>
    <rotation>0</rotation>
    <scale>1</scale>
    <width>0</width>
    <height>0</height>
    <nomber>1</nomber>
    <name></name>
    <resultID>CSum:0:CResult:0</resultID>
    <argumentID>CTransLink:0:CArgument:0</argumentID>
   </properties>
   <children/>
  </element>
  <element nodeType="rootNode" id="CLink:2" typeID="CLink">
   <properties>
    <objectName>CLink</objectName>
    <opacity>1</opacity>
    <enabled>true</enabled>
    <visible>true</visible>
    <x>0</x>
    <y>0</y>
    <z>0</z>
    <rotation>0</rotation>
    <scale>1</scale>
    <width>0</width>
    <height>0</height>
    <nomber>2</nomber>
    <name></name>
    <resultID>CTransLink:0:CResult:0</resultID>
    <argumentID>CCSVOut:0:CArgument:0</argumentID>
   </properties>
   <children/>
  </element>
  <element nodeType="rootNode" id="CLink:3" typeID="CLink">
   <properties>
    <objectName>CLink</objectName>
    <opacity>1</opacity>
    <enabled>true</enabled>
    <visible>true</visible>
    <x>0</x>
    <y>0</y>
    <z>0</z>
    <rotation>0</rotation>
    <scale>1</scale>
    <width>0</width>
    <height>0</height>
    <nomber>3</nomber>
    <name></name>
    <resultID>CTransLink:0:CResult:0</resultID>
    <argumentID>CTransLink:1:CArgument:0</argumentID>
   </properties>
   <children/>
  </element>
  <element nodeType="rootNode" id="CLink:4" typeID="CLink">
   <properties>
    <objectName>CLink</objectName>
    <opacity>1</opacity>
    <enabled>true</enabled>
    <visible>true</visible>
    <x>0</x>
    <y>0</y>
    <z>0</z>
    <rotation>0</rotation>
    <scale>1</scale>
    <width>0</width>
    <height>0</height>
    <nomber>4</nomber>
    <name></name>
    <resultID>CTransLink:1:CResult:0</resultID>
    <argumentID>CSum:0:CArgument:2</argumentID>
   </properties>
   <children/>
  </element>
 </elements>
</body>
